name: monthly-build
on:
  schedule:
    - cron: "0 4 1 * *"

jobs:
  monthly-build-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        go-version: "1.17.1"
      - run: |
          go run main.go
      - run: |
          git add .
          D=`date +"%Y-%m-%d"`
          git commit -m "${D} build"
