name: monthly-build
on:
  schedule:
    - cron: "0 4 1 * *"
  push:
    branches:
      - master

jobs:
  monthly-build-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.1"
      - run: |
          go run main.go
      - run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "Faryne"
          A=$(printf "%d" `git status | grep nothing | wc -l`)
          if [ "${A}" == "1" ]; then
            git add .
            D=`date +"%Y-%m-%d"`
            git commit -m "${D} build"
            git push origin master
          fi;
